# Generated by Django 2.2.2 on 2019-06-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Net', '0002_auto_20190616_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastfeed',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcastfeed',
            name='feedname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='podcastfeed',
            name='feedurl',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='podcastfeed',
            name='pod',
            field=models.ForeignKey(blank=True, null=True, on_delete='set_null', to='Net.Podcast'),
        ),
        migrations.AddField(
            model_name='podcastfeed',
            name='thumb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
