# Generated by Django 2.2.2 on 2019-06-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Net', '0005_auto_20190620_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='channelName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
