# Generated by Django 2.2.2 on 2019-06-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Net', '0008_auto_20190620_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.AddField(
            model_name='content',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Net.content',),
        ),
    ]
