# Generated by Django 2.2.2 on 2019-06-20 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Net', '0009_auto_20190620_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FundingPlatform',
            fields=[
                ('platform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Net.Platform')),
            ],
            bases=('Net.platform',),
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastHostship',
            fields=[
                ('hostship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Net.Hostship')),
            ],
            bases=('Net.hostship',),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('platform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Net.Platform')),
            ],
            bases=('Net.platform',),
        ),
        migrations.DeleteModel(
            name='YoutubeChannel',
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('pod', 'Podcast'), ('yt', 'YouTube'), ('lv', 'Live Show'), ('pm', 'Premium Content')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Net.content',),
        ),
    ]
