# Generated by Django 2.2.2 on 2019-06-20 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Net', '0010_auto_20190620_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('episode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Net.Episode')),
            ],
            bases=('Net.episode',),
        ),
        migrations.CreateModel(
            name='YoutubeEpisode',
            fields=[
                ('episode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Net.Episode')),
            ],
            bases=('Net.episode',),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('pod', 'Podcast'), ('yt', 'YouTube'), ('lv', 'Live Show'), ('pm', 'Premium Content'), ('sm', 'Social Media')], max_length=4, null=True),
        ),
    ]
