# Generated by Django 2.2.2 on 2019-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Net', '0011_auto_20190620_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostship',
            name='Pod',
        ),
        migrations.AddField(
            model_name='hostship',
            name='Content',
            field=models.ForeignKey(blank=True, null=True, on_delete='set_null', to='Net.Content'),
        ),
    ]
