# Generated by Django 2.2.2 on 2019-06-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Net', '0012_auto_20190620_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastfeed',
            name='pod',
            field=models.ForeignKey(blank=True, null=True, on_delete='set_null', to='Net.Content'),
        ),
    ]
